# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.5.2-jdk-7

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - (cd $HOME/.m2; wget http://resources.cumulocity.com/maven/repository/settings.xml; cp settings.xml settings-docker.xml)
          - ssh -N -f -L 8081:localhost:8081 -L 8080:localhost:8080 eickler@jenkins.cumulocity.com
          - mvn -B deploy # -B batch mode makes Maven less verbose