apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: "ci-registry-pull"
  containers:
    - name: "java"
      image: "registry.stage.c8y.io/ci/jdk:11"
      command: ["/bin/sh"]
      args: ["-c", "cat"]
      tty: true
      env:
        - name: JENKINS_URL
          value: http://jenkins.ci.svc.cluster.local:8080/
        - name: MAVEN_USER_HOME
          value: /home/jenkins/agent
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      workingDir: "/home/jenkins/agent"
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
